// export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
// export const REGISTER_FAIL = "REGISTER_FAIL";
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_FAIL = "LOGIN_FAIL";
// export const LOGOUT = "LOGOUT";

export const GET_ORGANISATION = "GET_ORGANISATION";
export const AddORGANISATION_SUCCESS = "AddORGANISATION_SUCCESS";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const  DELETE_ORGANISATION= "DELETE_ORGANISATION";
export const UPDATE_ORGANISATION="UPDATE_ORGANISATION";
export const GET_SINGLE_ORGANISATION="GET_SINGLE_ORGANISATION";
export const GET_ORGANISATIONFORUSER="GET_ORGANISATIONFORUSER";
export const Follow_Organisation="Follow_Organisation";
