export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const GET_PROFILE ="GET_PROFILE";
export const UPDATE = "UPDATE";
export const REFRESH_USER = "REFRESH_USER";
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const DELETE_USER = "DELETE_USER";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
 export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
  export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
  export const SHOW_ALL_POSTS = "SHOW_ALL_POSTS"
  export const NOTIFICATION = "NOTIFICATION";
  export  const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS"
  export const  NEW_PASSWORD_FAILED = "NEW_PASSWORD_FAILED"
  export const  EMAIL_VERIFIED_SUCCESS = "EMAIL_VERIFIED_SUCCESS"
  export const  EMAIL_VERIFIED_FAILED= "EMAIL_VERIFIED_FAILED"

export const  FETCHING_USERS_SUCCESS = "FETCHING_USERS_SUCCESS"
export const  FETCHING_USERS_FAILED= "FETCHING_USERS_FAILED"
export const  GET_USERS= "GET_USERS"
export const  DELETING_USER_SUCCESS= "DELETING_USER_SUCCESS"
export const  DELETING_USER_FAILED= "DELETING_USER_FAILED"
export const  USER_BAN_SUCCESS= "USER_BAN_SUCCESS"
export const  USER_BAN_FAILED= "USER_BAN_FAILED"
export const  USER_UNBAN_SUCCESS= "USER_UNBAN_SUCCESS"
export const  USER_UNBAN_FAILED= "USER_UNBAN_FAILED"

export const  MAKE_USER_ADMIN_SUCCESS = "MAKE_USER_ADMIN_SUCCESS"
export const  MAKE_USER_ADMIN_FAILED = "MAKE_USER_ADMIN_FAILED"

export const  USER_FETCHED_SUCCESS = "USER_FETCHED_SUCCESS"
export const  USER_FETCHED_FAILED = "USER_FETCHED_FAILED"

export const  USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const  USER_UPDATE_FAILED = "USER_UPDATE_FAILED"





